# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'LYNetworkTool' do
  use_frameworks!
  pod 'AFNetworking'
	
end

target 'LYNetworkToolTests' do
  use_frameworks!
  pod 'AFNetworking'

end
